name: Build & Publish Release APK

on:
  push:
    branches: [ mobile-implementation, main ]

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: android/app/build/outputs/apk/release/*.apk
    - name: Release APK
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: android/app/build/outputs/apk/release/*.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}