name: Build Mobile APK
on:
  push:
    branches: [ mobile-implementation, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Validate Android Project Structure
      run: |
        echo "Checking project structure..."
        if [ ! -d "android" ]; then
          echo "ERROR: Android directory not found!"
          ls -la
          exit 1
        fi
        
        if [ ! -f "android/build.gradle" ]; then
          echo "ERROR: android/build.gradle not found!"
          ls -la android/
          exit 1
        fi
        
        if [ ! -f "android/gradlew" ]; then
          echo "ERROR: android/gradlew not found!"
          ls -la android/
          exit 1
        fi
        
        echo "Project structure validated successfully"
    
    - name: Make gradlew executable
      run: |
        cd android
        chmod +x gradlew
    
    - name: Build Debug APK
      id: build_apk
      run: |
        echo "Starting APK build process..."
        cd android
        ./gradlew assembleDebug --stacktrace
        
        # Check if APK was actually created
        if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
          echo "APK build successful"
          echo "apk_status=success" >> $GITHUB_OUTPUT
        else
          echo "ERROR: APK file not found after build"
          echo "Looking for APK files..."
          find . -name "*.apk" 2>/dev/null || echo "No APK files found"
          echo "apk_status=failed" >> $GITHUB_OUTPUT
          exit 1
        fi
    
    - name: List APK directory contents
      if: success()
      run: |
        cd android
        echo "Contents of APK output directory:"
        ls -la app/build/outputs/apk/debug/ 2>/dev/null || echo "APK directory not found"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: lemonai-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Build Logs (if build failed)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          android/app/build/reports/
